/*
데이터베이스설계 과제
작성자: 김세연
작성일: 2019-05-23

SQL 설명: 본사DB의 코드 테이블에 코드들을 삽입한다.
*/

--DIVCD(구분코드)에 구분코드 삽입
INSERT INTO DIVCD(DIVCD, DIVCD_NAME) VALUES('CD05', '주문상태');
INSERT INTO DIVCD(DIVCD, DIVCD_NAME) VALUES('CD06', '반품상태');
INSERT INTO DIVCD(DIVCD, DIVCD_NAME) VALUES('CD09', '포인트변경구분');
INSERT INTO DIVCD(DIVCD, DIVCD_NAME) VALUES('CD11', '물품구분');

--주문상태 상세코드 삽입
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD05', '01', '주문준비중');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD05', '02', '주문거절');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD05', '03', '배송중');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD05', '04', '배송완료');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD05', '05', '확인완료');

--반품상태 상세코드 삽입
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD06', '01', '반품준비중');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD06', '02', '반품거절');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD06', '03', '반품처리중');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD06', '04', '반품수거중');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD06', '05', '반품수거완료');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD06', '06', '반품완료');

--포인트변경구분 상세코드 삽입
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD09', '01', '결제사용');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD09', '02', '결제적립');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD09', '03', '최초 가입 적립');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD09', '04', '이벤트');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD09', '05', '기타');

--물품구분 상세코드 삽입
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD11', '001', '과자');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD11', '002', '아이스크림');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD11', '003', '컵라면');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD11', '004', '봉지라면');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD11', '005', '김밥');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD11', '006', '즉석냉장식품');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD11', '007', '즉석냉동식품');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD11', '008', '탄산음료');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD11', '009', '비탄산음료');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD11', '010', '술');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD11', '011', '담배');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD11', '012', '생필품');
INSERT INTO DTCD(DIVCD, DTCD, CD_NAME) VALUES('CD11', '013', '기타');